name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isometric.svg
          base: "activity"
          use_prebuilt_image: yes
          plugin_isometric: yes
          plugin_isometric_sections: "activity+repositories"
